### ISSUE TITLE
Animation freezes in android

### ISSUE THREAD

**Issue by Peretz30** [fnzc/react-native-pincode#36]
I am using Android with USB debugging. 
And animation, for example, of wrong pin are really laggy and have low fps. In builded app it's a little better, but still.
Can you please optimize animation for better perfomance?

**Comment by Baskerville42** [comment]
The same issue with Android Emulator and iOS Emulator

**Comment by Haskkor** [comment]
Looks like it's ok without the debugger for everyone. So closing it :)

**Comment by AlphaJuliettOmega** [comment]
@Haskkor just out of curiousity, how do you debug an application if you can't run the debugger?

I can't enter the pin, the screen is so slow
Double clicking the pin buttons _sometimes_ fires a click event
Triple clicking the pin buttons _most of the time_ will fire a click event

Meaning I can enter about 3 characters of the 4 character pin, but the fourth one is a complete gamble (often the third character enters twice for whatever reason)

Subsequently I can't debug my app at all without hard-coding a pin-screen work-around

Any advice would be appreciated re. debugging an application with this pin screen integrated.

**Comment by AlphaJuliettOmega** [comment]
Hmmm, it seems to be _usable_ after some small changes to the setup

As per this S/O question:
https://stackoverflow.com/a/51334853/5334945

- I set my Emulator's Clock 1 minute ahead of the PC it's running on
- Enabled Developer Options and disabled all animation options possible (probably no effect since it's to do with the Application windows)
- disabled Redux Devtools Chrome extension (also probably no effect but just noting)

Now instead of clicks not registering at all, they're just really slow ~ 2-4 seconds delayed, but reliable at least.
Can debug like this :)
