### ISSUE TITLE
Redirection inside onFail results in warning about  setting State on an unmounted component

### ISSUE THREAD

**Issue by tkulpa** [fnzc/react-native-pincode#54]
https://github.com/fnzc/react-native-pincode/blob/master/src/PinCodeEnter.tsx#L143

Maybe this code could be moved at very end so it will be safe to unmount component on fails and this would also allow for user to manage _pinAttemptsAsyncStorageName_ property in _AsyncStorage_ on thier own

**Comment by Haskkor** [comment]
Moving this at the end doesn't fix the warning.
Putting a delay in the onFail removes it so I'll keep on investigating to find what is updating the component after the onFail.

```
      <View style={styles.container}>
        {this.state.ok && <PINCode status={'enter'} timeLocked={5000} onFail={async () => {
          await delay(2000)
          this.setState({ok: false})
        }}/>}
      </View>
```

**Comment by Haskkor** [comment]
So it's because of the 'shake' animation when the user fails. It's you don't wait ~1500 ms, you get the warning.
I don't know if you need the animation or not.
I could put a 1500ms delay before firing the `onFail` prop, or I could remove the animation based on a new property...or something else I can't think of :p

What do you think? 

Cheers,
Jeremy

**Comment by tkulpa** [comment]
It think 1500ms delay will be straight forward solution for this :)

**Comment by Haskkor** [comment]
Fixed in the new version :).

Cheers,
Jeremy
